a=3
b=4
try:                            #if in try there is error both except and else will be excecuted...
    print(a/b)
except:
    print(a/b)
else:
    print("sssss")
x=2
try:
    print(x)
except:
    print("An exception occurred")